### ISSUE TITLE
Delete this Repository

### ISSUE THREAD

**Issue by LastTargaryen** [jiaxiangc/ComfyUI-ResAdapter#1]
If you're delayed from releasing code, or don't plan on releasing code,

DON'T OPEN A REPOSITORY. It's EXTREMELY ABUSIVE TO GITHUB'S PURPOSE.

GITHUB IS NOT YOUR FREE ADVERTISEMENT PLATFORM.

NO ONE ENJOYS SEEING AN EMPTY REPOSITORY THAT IS LABELED AS CONTAINING IMPORTANT TECHNOLOGY

THANKS

**Comment by jiaxiangc** [comment]
@LastTargaryen 
Hello, I will release the code this month, please be patient. I have no intention of advertising on Github.

**Comment by jiaxiangc** [comment]
@LastTargaryen 
The reason I delayed releasing the ComfyUI code is that we need to prioritize promoting the code internally before releasing it. Please wait.

**Comment by LastTargaryen** [comment]
> @LastTargaryen The reason I delayed releasing the ComfyUI code is **that we need to prioritize promoting the code internally** before releasing it. Please wait.

I appreciate that you're trying to provide me with a legitimate response.

...but what in the world does "we need to prioritize promoting the code internally" mean? I wasn't asking for reasons, nor was I demanding an explanation at all. But you've offered an explanation, so this is me asking you,

What do you mean by that?

**Comment by jiaxiangc** [comment]
@LastTargaryen 
We will open source it as soon as possible, but we need to prioritize using ComfyUI-ResAdapter within our company.

**Comment by LastTargaryen** [comment]
Thank you for the direct response. 
We very much await the validation of this repository. 
As it stands now, this repository is currently being used as a place-holding announcement for material that that you claim is authored by you and completed, but is conspicuously withheld due to corporate interest. I just want to clarify that the philosophy of open source does not include consideration of corporate interest prior to complete, costless release. 
It is true that the definitions of such philosophies has gray areas--it may be wise for you to be aware of that, as well.

Because no one in this community sees your repository and thinks "oh wow, I can't wait for this giant company to do whatever it's going to do with this product so we can get whatever they don't determine is profitable!"

Thank you for your hard work in creating this...but you could have just waited to create the repository when you were certain that you are permitted to release the code.

**Comment by jiaxiangc** [comment]
I think you are absolutely right. I will pay attention to it in future open source. At the same time, I will release the code as soon as possible, thank you for your suggestions.

**Comment by jiaxiangc** [comment]
@LastTargaryen We have released the code.
