### ISSUE TITLE
我不知道是你们发错了还是我用的不对，我甚至觉得他不如原版，有遇到同样情况的朋友吗

### ISSUE THREAD

**Issue by chenpipi0807** [jiaxiangc/ComfyUI-ResAdapter#11]
`{
  "last_node_id": 19,
  "last_link_id": 36,
  "nodes": [
    {
      "id": 7,
      "type": "VAEDecode",
      "pos": [
        1720,
        140
      ],
      "size": {
        "0": 210,
        "1": 46
      },
      "flags": {},
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 9,
          "label": "Latent"
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 13,
          "label": "VAE"
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            8
          ],
          "shape": 3,
          "label": "图像"
        }
      ],
      "properties": {
        "Node name for S&R": "VAEDecode"
      }
    },
    {
      "id": 9,
      "type": "SaveImage",
      "pos": [
        2011,
        221
      ],
      "size": {
        "0": 322.2373046875,
        "1": 365.31610107421875
      },
      "flags": {},
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 8,
          "label": "图像"
        }
      ],
      "properties": {},
      "widgets_values": [
        "ComfyUI"
      ]
    },
    {
      "id": 13,
      "type": "VAEDecode",
      "pos": [
        1733,
        -196
      ],
      "size": {
        "0": 210,
        "1": 46
      },
      "flags": {},
      "order": 13,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 23,
          "label": "Latent"
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 22,
          "label": "VAE"
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            24
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "图像"
        }
      ],
      "properties": {
        "Node name for S&R": "VAEDecode"
      }
    },
    {
      "id": 6,
      "type": "EmptyLatentImage",
      "pos": [
        570,
        240
      ],
      "size": {
        "0": 315,
        "1": 106
      },
      "flags": {},
      "order": 0,
      "mode": 0,
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            7,
            21
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "Latent"
        }
      ],
      "properties": {
        "Node name for S&R": "EmptyLatentImage"
      },
      "widgets_values": [
        576,
        1152,
        2
      ]
    },
    {
      "id": 18,
      "type": "VideoLinearCFGGuidance",
      "pos": [
        529,
        -75
      ],
      "size": {
        "0": 315,
        "1": 58
      },
      "flags": {},
      "order": 3,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 31,
          "label": "模型"
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            32
          ],
          "shape": 3,
          "label": "模型",
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "VideoLinearCFGGuidance"
      },
      "widgets_values": [
        4
      ]
    },
    {
      "id": 17,
      "type": "VideoLinearCFGGuidance",
      "pos": [
        879.2442671864294,
        -199.20584403841656
      ],
      "size": {
        "0": 315,
        "1": 58
      },
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 29,
          "label": "模型"
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            30
          ],
          "shape": 3,
          "label": "模型",
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "VideoLinearCFGGuidance"
      },
      "widgets_values": [
        4
      ]
    },
    {
      "id": 14,
      "type": "SaveImage",
      "pos": [
        2003,
        -195
      ],
      "size": {
        "0": 331.33795166015625,
        "1": 365.7622985839844
      },
      "flags": {},
      "order": 14,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 24,
          "label": "图像"
        }
      ],
      "properties": {},
      "widgets_values": [
        "ComfyUI"
      ]
    },
    {
      "id": 19,
      "type": "CR Seed",
      "pos": [
        918,
        -20
      ],
      "size": {
        "0": 315,
        "1": 102
      },
      "flags": {},
      "order": 1,
      "mode": 0,
      "outputs": [
        {
          "name": "seed",
          "type": "INT",
          "links": [
            33,
            34
          ],
          "shape": 3,
          "label": "随机种",
          "slot_index": 0
        },
        {
          "name": "show_help",
          "type": "STRING",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CR Seed"
      },
      "widgets_values": [
        509489548871484,
        "randomize"
      ]
    },
    {
      "id": 5,
      "type": "KSampler",
      "pos": [
        1421,
        357
      ],
      "size": {
        "0": 315,
        "1": 474
      },
      "flags": {},
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 32,
          "label": "模型"
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 5,
          "label": "正面条件"
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 6,
          "label": "负面条件"
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 7,
          "label": "Latent"
        },
        {
          "name": "seed",
          "type": "INT",
          "link": 34,
          "widget": {
            "name": "seed"
          },
          "label": "随机种"
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            9
          ],
          "shape": 3,
          "label": "Latent"
        }
      ],
      "properties": {
        "Node name for S&R": "KSampler"
      },
      "widgets_values": [
        693786953489814,
        "randomize",
        30,
        5,
        "euler_ancestral",
        "normal",
        1
      ]
    },
    {
      "id": 10,
      "type": "ResAdapterLoader",
      "pos": [
        580,
        -520
      ],
      "size": {
        "0": 315,
        "1": 126
      },
      "flags": {},
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 14,
          "label": "model"
        },
        {
          "name": "clip",
          "type": "CLIP",
          "link": 16,
          "label": "clip"
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            29
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "MODEL"
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [],
          "shape": 3,
          "slot_index": 1,
          "label": "CLIP"
        }
      ],
      "properties": {
        "Node name for S&R": "ResAdapterLoader"
      },
      "widgets_values": [
        "resadapter_v1_sd1.5",
        1,
        1
      ],
      "color": "#322",
      "bgcolor": "#533"
    },
    {
      "id": 3,
      "type": "CLIPTextEncode",
      "pos": [
        913,
        137
      ],
      "size": {
        "0": 400,
        "1": 200
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 2,
          "label": "CLIP"
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            5,
            35
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "条件"
        }
      ],
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "three of the image,(1asian_girl, full_body, standing, facing forward, hands_natural_down, white_background),A girl with a pink hat,yellow short-sleeves,carrying a colorful schoolbag,green shorts,red hair,and colorful sneakers,Realistic 3D cartoon style rendering,girl,whole body,standing,looking up,summer trendy fashion clothing,candy-colored clothes,new popular portrait,fashion illustration,bright colors,neon realistic,bubble mart production,glossy and delicate,clean background,3D rendering,OC rendering,8K,Maintain consistency and uniformity,"
      ]
    },
    {
      "id": 4,
      "type": "CLIPTextEncode",
      "pos": [
        930,
        390
      ],
      "size": {
        "0": 400,
        "1": 200
      },
      "flags": {
        "collapsed": false
      },
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 3,
          "label": "CLIP"
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            6,
            36
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "条件"
        }
      ],
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        ""
      ]
    },
    {
      "id": 2,
      "type": "CLIPSetLastLayer",
      "pos": [
        540,
        100
      ],
      "size": {
        "0": 315,
        "1": 58
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 15,
          "label": "CLIP"
        }
      ],
      "outputs": [
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            2,
            3,
            16
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "CLIP"
        }
      ],
      "properties": {
        "Node name for S&R": "CLIPSetLastLayer"
      },
      "widgets_values": [
        -1
      ]
    },
    {
      "id": 1,
      "type": "CheckpointLoaderSimple",
      "pos": [
        80,
        90
      ],
      "size": {
        "0": 375.30194091796875,
        "1": 107.8841781616211
      },
      "flags": {},
      "order": 2,
      "mode": 0,
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            14,
            31
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "模型"
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            15
          ],
          "shape": 3,
          "slot_index": 1,
          "label": "CLIP"
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            13,
            22
          ],
          "shape": 3,
          "slot_index": 2,
          "label": "VAE"
        }
      ],
      "properties": {
        "Node name for S&R": "CheckpointLoaderSimple"
      },
      "widgets_values": [
        "chilloutmix_NiPrunedFp32Fix.safetensors"
      ]
    },
    {
      "id": 12,
      "type": "KSampler",
      "pos": [
        1360,
        -390
      ],
      "size": {
        "0": 315,
        "1": 474
      },
      "flags": {},
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 30,
          "label": "模型"
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 35,
          "label": "正面条件"
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 36,
          "label": "负面条件"
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 21,
          "label": "Latent"
        },
        {
          "name": "seed",
          "type": "INT",
          "link": 33,
          "widget": {
            "name": "seed"
          },
          "label": "随机种",
          "slot_index": 4
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            23
          ],
          "shape": 3,
          "slot_index": 0,
          "label": "Latent"
        }
      ],
      "properties": {
        "Node name for S&R": "KSampler"
      },
      "widgets_values": [
        663548888203913,
        "randomize",
        30,
        5,
        "euler_ancestral",
        "normal",
        1
      ]
    }
  ],
  "links": [
    [
      2,
      2,
      0,
      3,
      0,
      "CLIP"
    ],
    [
      3,
      2,
      0,
      4,
      0,
      "CLIP"
    ],
    [
      5,
      3,
      0,
      5,
      1,
      "CONDITIONING"
    ],
    [
      6,
      4,
      0,
      5,
      2,
      "CONDITIONING"
    ],
    [
      7,
      6,
      0,
      5,
      3,
      "LATENT"
    ],
    [
      8,
      7,
      0,
      9,
      0,
      "IMAGE"
    ],
    [
      9,
      5,
      0,
      7,
      0,
      "LATENT"
    ],
    [
      13,
      1,
      2,
      7,
      1,
      "VAE"
    ],
    [
      14,
      1,
      0,
      10,
      0,
      "MODEL"
    ],
    [
      15,
      1,
      1,
      2,
      0,
      "CLIP"
    ],
    [
      16,
      2,
      0,
      10,
      1,
      "CLIP"
    ],
    [
      21,
      6,
      0,
      12,
      3,
      "LATENT"
    ],
    [
      22,
      1,
      2,
      13,
      1,
      "VAE"
    ],
    [
      23,
      12,
      0,
      13,
      0,
      "LATENT"
    ],
    [
      24,
      13,
      0,
      14,
      0,
      "IMAGE"
    ],
    [
      29,
      10,
      0,
      17,
      0,
      "MODEL"
    ],
    [
      30,
      17,
      0,
      12,
      0,
      "MODEL"
    ],
    [
      31,
      1,
      0,
      18,
      0,
      "MODEL"
    ],
    [
      32,
      18,
      0,
      5,
      0,
      "MODEL"
    ],
    [
      33,
      19,
      0,
      12,
      4,
      "INT"
    ],
    [
      34,
      19,
      0,
      5,
      4,
      "INT"
    ],
    [
      35,
      3,
      0,
      12,
      1,
      "CONDITIONING"
    ],
    [
      36,
      4,
      0,
      12,
      2,
      "CONDITIONING"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {},
  "version": 0.4
}`

**Comment by jiaxiangc** [comment]
麻烦提供一下你的具体的workflow json文件，我来复现一下。

**Comment by jiaxiangc** [comment]
我最近训练了resadapter_v2_sd1.5，改进了训练方案。相比resadapter_v1_sd1.5，在128～1024覆盖更密集的分辨率和比例。这里给出几个 example，我整理好后会放出来。
![comfyui-01](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/76088379/a5c19a9b-c5f9-416a-95cd-19acc2a2bbd4)
![comfyui-2](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/76088379/bcda3280-585f-45b5-a1fa-4c0e51d414fd)
![comfyui-03](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/76088379/adfe8c29-394e-4007-9a3a-b4dedafa4547)

**Comment by jiaxiangc** [comment]
We have update the latest resadapter_v1_sd1.5
https://huggingface.co/jiaxiangc/res-adapter/tree/main/resadapter_v1_sd1.5

**Comment by jiaxiangc** [comment]
I also find bad result with lcm-lora, ip-adapter and controlnet in ComfyUI. But it generate good results in diffusers.
I think it is caused by our comfyui code, maybe normalization conflict or lora conflict.
I am fixing these bugs.

**Comment by jiaxiangc** [comment]
We have fixing model loading bugs, providing more workflows. Detailed information is [here](https://github.com/jiaxiangc/ComfyUI-ResAdapter).

And there are resadapter_v2 in [huggingface](https://huggingface.co/jiaxiangc/res-adapter/tree/main).

**Comment by jiaxiangc** [comment]
LCM-LoRA:
https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/162297627/46ce4224-ab4d-4890-abc8-00b716dcb29a

**Comment by chenpipi0807** [comment]
I see you recently updated the project, I'll give it a try,
