### ISSUE TITLE
bad result of SD1.5 when apply ipadapter

### ISSUE THREAD

**Issue by whmc76** [jiaxiangc/ComfyUI-ResAdapter#14]
i'm using the latest 2024/4/3 version， but it is not so good,

![image](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/129386342/2010297f-0be9-491d-8970-35a72790c248)

**Comment by whmc76** [comment]
![image](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/129386342/c5ad8893-2f3f-4d13-a0d1-bb495d9aebb8)
even lower weight still bad image

**Comment by jiaxiangc** [comment]
Yes, I find bad result with lcm-lora, ip-adapter and controlnet in ComfyUI. 
But it does not appear in diffusers. I think it is caused by our comfyui code, maybe normalization conflict or lora conflict. 
I am fixing these bugs.

**Comment by whmc76** [comment]
> Yes, I find bad result with lcm-lora, ip-adapter and controlnet in **ComfyUI**. But it generate good results in **diffusers**. I think it is caused by our comfyui code, maybe normalization conflict or lora conflict. I am fixing these bugs.

looking forward good news,大佬加油

**Comment by jiaxiangc** [comment]
Try to this. https://github.com/jiaxiangc/ComfyUI-ResAdapter/blob/main/examples/resadapter_ipadapter_workflow.json

https://github.com/jiaxiangc/ComfyUI-ResAdapter/blob/main/misc/resadapter_ipadapter.png?raw=true
