### ISSUE TITLE
This month? Right?

### ISSUE THREAD

**Issue by wudideasdf** [jiaxiangc/ComfyUI-ResAdapter#3]

**Comment by blepping** [comment]
@wudideasdf if you want to use it now, you can try my experimental unet patch node: https://github.com/blepping/ComfyUI-ApplyResAdapterUnet

note: i am just a random person, no affiliation with the ResAdapter project.

**Comment by jiaxiangc** [comment]
There are some people to contribute to ComfyUI-ResAdapter, i will pull requests in this month.

**Comment by jiaxiangc** [comment]
@wudideasdf I will release code in this month.

**Comment by jiaxiangc** [comment]
@wudideasdf We have released the code.
