### ISSUE TITLE
Here is demo video.

### ISSUE THREAD

**Issue by fengyuzzz** [jiaxiangc/ComfyUI-ResAdapter#4]
I provide a demo video, which is helpful for others to use ComfyUI-ResAdapter. @jiaxiangc 

https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/162297627/adc6ec6d-bc43-4ecc-9d3a-2b3c31aeef6c

**Comment by jiaxiangc** [comment]
Thanks for your contribution.

**Comment by kakachiex2** [comment]
I get different result with dreamshaper lcm Normal Render looks better than ResAdapter render but ResAdapter sticks more to the prompt

![Screenshot 2024-04-01 210728](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/1762112/26154189-90ba-4a87-a656-d991a2f109c8)
![Screenshot 2024-04-01 211307](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/1762112/6224e6ad-43fa-462b-b020-943e99f45303)

**Comment by kakachiex2** [comment]
This is the prompt for the last image
:: | bare shoulder,sexy, cleavage,1 girl,portrait, curly hair,simple background, (masterpiece,best quality),lips, spark ,niji style, camisole, Pullover Sweater , realistic,in the villa, steamy, steam , sad,deep red gradient background,
|

**Comment by jiaxiangc** [comment]
> Just wondering why the clip text encode nodes don't use the clip from resadapter node? Any particular reason?

If you only use resadapter loader, you need to use clip. But we use resadapter and baseline, so I directly use baseline clip information.

**Comment by jiaxiangc** [comment]
> I get different result with dreamshaper lcm Normal Render looks better than ResAdapter render but ResAdapter sticks more to the prompt
> 
> ![Screenshot 2024-04-01 210728](https://private-user-images.githubusercontent.com/1762112/318609526-26154189-90ba-4a87-a656-d991a2f109c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzA5MTAsIm5iZiI6MTcxMjAzMDYxMCwicGF0aCI6Ii8xNzYyMTEyLzMxODYwOTUyNi0yNjE1NDE4OS05MGJhLTRhODctYTY1Ni1kOTkxYTJmMTA5YzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDQwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjUxZmRhMDlhYjk2Y2RmYjk3YTRjNTYxNDczODA1NzhiYzc0MTBkMWRkODZiM2JlZGQwNTMyMzdiYzU1Mzc3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LRyiZIWOsLQTXSFr1y-cvXvaTpqR9yBB1Tdv4Kkelo0) ![Screenshot 2024-04-01 211307](https://private-user-images.githubusercontent.com/1762112/318609551-6224e6ad-43fa-462b-b020-943e99f45303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzA5MTAsIm5iZiI6MTcxMjAzMDYxMCwicGF0aCI6Ii8xNzYyMTEyLzMxODYwOTU1MS02MjI0ZTZhZC00M2ZhLTQ2MmItYjAyMC05NDNlOTlmNDUzMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDQwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNjODkxNjM1OTY3ZmI4MWIxYTE3NWJlZmNiMzlkMDA5YzgzZmI2YTFmN2QxMjQ1OTJhMTgyNWNkNTA5MTAxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GOZj5NikOlIbz5V7xtBewa4ad2EOzSGhqBJlTTwYSPo)



> I get different result with dreamshaper lcm Normal Render looks better than ResAdapter render but ResAdapter sticks more to the prompt
> 
> ![Screenshot 2024-04-01 210728](https://private-user-images.githubusercontent.com/1762112/318609526-26154189-90ba-4a87-a656-d991a2f109c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzA5MTAsIm5iZiI6MTcxMjAzMDYxMCwicGF0aCI6Ii8xNzYyMTEyLzMxODYwOTUyNi0yNjE1NDE4OS05MGJhLTRhODctYTY1Ni1kOTkxYTJmMTA5YzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDQwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjUxZmRhMDlhYjk2Y2RmYjk3YTRjNTYxNDczODA1NzhiYzc0MTBkMWRkODZiM2JlZGQwNTMyMzdiYzU1Mzc3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LRyiZIWOsLQTXSFr1y-cvXvaTpqR9yBB1Tdv4Kkelo0) ![Screenshot 2024-04-01 211307](https://private-user-images.githubusercontent.com/1762112/318609551-6224e6ad-43fa-462b-b020-943e99f45303.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzA5MTAsIm5iZiI6MTcxMjAzMDYxMCwicGF0aCI6Ii8xNzYyMTEyLzMxODYwOTU1MS02MjI0ZTZhZC00M2ZhLTQ2MmItYjAyMC05NDNlOTlmNDUzMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDQwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNjODkxNjM1OTY3ZmI4MWIxYTE3NWJlZmNiMzlkMDA5YzgzZmI2YTFmN2QxMjQ1OTJhMTgyNWNkNTA5MTAxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GOZj5NikOlIbz5V7xtBewa4ad2EOzSGhqBJlTTwYSPo)

Can you share your workflow, i try to reproduce it.
However, we find that resadapter is not compatible with accelerate lora in resolution extrapolation. Because resadapter is trained in fine-tuning. I am considering to train resadapter with lcm, asd, tcd and so on.
Now, i am training new resadapter for broading ratio.

**Comment by wencxxxxxx** [comment]
> > 只是想知道为什么剪辑文本编码节点不使用来自resadapter节点的剪辑？有什么特别的原因吗？
> 
> 如果只使用resadapter loader，则需要使用clip。但是我们使用resadapter和baseline，所以我直接使用基线剪辑信息。



> > Just wondering why the clip text encode nodes don't use the clip from resadapter node? Any particular reason?
> 
> If you only use resadapter loader, you need to use clip. But we use resadapter and baseline, so I directly use baseline clip information.

I don't know what you mean by that. Can you be more specific

**Comment by jiaxiangc** [comment]
The baseline worflow and resadapter workflow share the same text clip embedding.
However, there are bugs in this workflow with ip-adapter, controlnet and lcm-lora. I am fixing these bugs.

**Comment by wencxxxxxx** [comment]
Thank you for your help

**Comment by jiaxiangc** [comment]
We have fixing model loading bugs,  providing more workflows. Detailed information is [here](https://github.com/jiaxiangc/ComfyUI-ResAdapter).

 And there are resadapter_v2 in [huggingface](https://huggingface.co/jiaxiangc/res-adapter/tree/main).
