### ISSUE TITLE
为什么输出的图像内出现了两个人物

### ISSUE THREAD

**Issue by sakiyo18** [jiaxiangc/ComfyUI-ResAdapter#7]
![微信截图_20240331212026](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/39026267/8557bfd9-ae9b-4d46-b2c7-727331cf92f9)

**Comment by jiaxiangc** [comment]
你能提供具体的模型链接和workflow吗？我来尝试复现一下。

**Comment by jiaxiangc** [comment]
我可以给出一些使用建议：
1. ResAdapter主要是用来修正风格化模型的物体重复，它在一定的概率内可以修正图像。
2. 你需要调整好适合风格化模型的 scheduler、step、sampler。
3. 你需要输入适合风格化模型的prompt，我们的实验发现如果prompt不能有效激发风格化模型的能力，修正成功的概率会相对低一些。
