### ISSUE TITLE
The sdxl comparison generation is very good. But compared to SD1.5, there is an issue

### ISSUE THREAD

**Issue by tanglup** [jiaxiangc/ComfyUI-ResAdapter#8]

**Comment by tanglup** [comment]
The three models of SD1.5 have no effect, but instead have deteriorated. I hope they can be improved

**Comment by jiaxiangc** [comment]
Can you provide more detailed information?

**Comment by tanglup** [comment]
> Can you provide more detailed information?

![a1](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/160642431/92652745-a490-474b-8046-cb65c5915faf)
![a2](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/160642431/fddbca29-cdfd-4b66-ae3f-3f2d2fb54d3c)
![a3](https://github.com/jiaxiangc/ComfyUI-ResAdapter/assets/160642431/6142eef5-ef8e-45b0-9697-1bd21907834f)

**Comment by jiaxiangc** [comment]
Oh, i know the reason. Because resadapter is not training on 256x1024 (1:4) ratio.
Thanks for your test, i will train resadapterv15 for broading ratio.

**Comment by jiaxiangc** [comment]
We have update the latest version of resadapter_v1_sdv15.https://huggingface.co/jiaxiangc/res-adapter/tree/main/resadapter_v1_sd1.5
Now we are training resadapter_v2_sdv15 for broad ratio.
